[package]
name = "giza-air"
version = "0.1.0"
edition = "2018"

[dependencies]
winter-air = "0.7.0"
winter-utils = "0.7.0"
giza_core = { package = "giza-core", path = "../core", version = "0.1", default-features = false }
serde = "1.0.137"
