[package]
name = "giza-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
winter-math = "0.7.0"
math = { version = "0.7.0", package = "winter-math", default-features = false }
winter-utils = "0.7.0"
ff = { version = "0.12", features = ["derive"] }
hex = "0.4"

